### ISSUE TITLE
Pisanje izvestaja

### ISSUE THREAD

**Issue by rastko-djordjevic-edu** [MATF-RG19/RG1-let-us-get-some-buckets#1]
Pisanje izvestaja je neophodno: videti uputstvo za pisanje i sta moraju da sadrze na mojoj strani.

**Comment by ivan-vrankovic** [comment]
Napisani izvestaji: 

1. Izvestaj o prethodnom commit-u u kom su implementirane teksture, osvetljenje i dodati materijali
2. Izvestaj o poslednjem commit-u u kom su implementirane tabla i mrezica kosa kao i animacije u slucaju pogotka
