### ISSUE TITLE
Readme.md

### ISSUE THREAD

**Issue by rastko-djordjevic-edu** [MATF-RG19/RG1-let-us-get-some-buckets#2]
U README.md fajlu se moraju nalaziti kratak opis projekta, opis buildovanja i pokretanja projekta (npr. koriscenjem makefile-a), sve bilblioteke koje su koriscene kao i kratko uputstvo kako ih instalirati.

**Comment by ivan-vrankovic** [comment]
U README.md fajlu se sada nalaze sve neophodne stvari.
